# Run `eas submit` for the latest build
name: EAS Submit

env:
  PRIVACY_POLICY_LINK: ${{ secrets.PRIVACY_POLICY_LINK }}
  GITHUB_LINK: ${{ secrets.REPO_LINK }}
  GITHUB_PROFILE_LINK: ${{ secrets.PROFILE_LINK }}
  APP_STORE_LINK: ${{ secrets.APP_STORE_LINK }}
  GOOGLE_PLAY_LINK: ${{ secrets.GOOGLE_PLAY_LINK }}
  SUPPORT_LINK: ${{ secrets.SUPPORT_LINK }}
  PROD_BUILD: ${{ secrets.PROD_BUILD }}

  EXPO_APP_SPECIFIC_PASSWORD: ${{ secrets.EXPO_APPLE_APP_SPECIFIC_PASSWORD }}
  GOOGLE_SERVICE_ACC_PRIVATE_KEY: ${{ secrets.GOOGLE_SERVICE_ACC_PRIVATE_KEY }}

on:
  # pull_request:
  #   branches: [ main ]

  # Run manually
  workflow_dispatch:
  workflow_call:

jobs:
  # Run `eas-prod` workflow
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Run `eas-prod` workflow
  #       uses: ./.github/workflows/eas-prod

  submit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          node-version: 16.x

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          token: ${{ secrets.EXPO_TOKEN }}
          eas-version: latest
          packager: yarn
      - name: Install dependencies
        run: yarn install

      - name: Submit to Google Play
        run: eas submit -p android --latest --profile production --non-interactive

      - name: Submit to App Store
        run: eas submit -p ios --latest --profile production --non-interactive