# Run `eas build` and `eas submit
name: EAS Production

env:
  APP_STORE_LINK: ${{ secrets.APP_STORE_LINK }}
  GOOGLE_PLAY_LINK: ${{ secrets.GOOGLE_PLAY_LINK }}
  PROD_BUILD: ${{ secrets.PROD_BUILD }}

  # EXPO_APP_SPECIFIC_PASSWORD: ${{ secrets.EXPO_APPLE_APP_SPECIFIC_PASSWORD }}

on:
  # pull_request:
  #   branches: [ main ]

  # Run manually
  workflow_dispatch:

jobs:
  build-and-submit-apple:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Build
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'yarn'
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          token: ${{ secrets.EXPO_TOKEN }}
          packager: yarn
          expo-cache: true
          expo-version: 5.3.0
          eas-version: latest
      - name: Install dependencies
        run: yarn install
      - name: Build on EAS
        run: eas build --profile production --platform ios --non-interactive

      # Submit
      - name: Submit to App Store
        run: eas submit -p ios --latest --profile production --non-interactive

  # Run `eas-prod` workflow
  build-and-submit-google:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Build
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'yarn'
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          token: ${{ secrets.EXPO_TOKEN }}
          packager: yarn
          expo-cache: true
          expo-version: 5.3.0
          eas-version: latest
      - name: Install dependencies
        run: yarn install
      - name: Build on EAS
        run: eas build --profile production --platform android --non-interactive

      # Submit
      - name: Submit to Google Play
        run: eas submit -p android --latest --profile production --non-interactive