# Run `eas build --profile production`
# This workflow will stay running until both builds complete
name: EAS Build Production

env:
  PRIVACY_POLICY_LINK: ${{ secrets.PRIVACY_POLICY_LINK }}
  GITHUB_LINK: ${{ secrets.REPO_LINK }}
  GITHUB_PROFILE_LINK: ${{ secrets.PROFILE_LINK }}
  APP_STORE_LINK: ${{ secrets.APP_STORE_LINK }}
  GOOGLE_PLAY_LINK: ${{ secrets.GOOGLE_PLAY_LINK }}
  SUPPORT_LINK: ${{ secrets.SUPPORT_LINK }}
  PROD_BUILD: ${{ secrets.PROD_BUILD }}

  # Pass in additional variables relating to ASC
  EXPO_APP_SPECIFIC_PASSWORD: ${{ secrets.EXPO_APPLE_APP_SPECIFIC_PASSWORD }}

on:
  # Run when pull request is opened
  # pull_request:
  #   types: [ opened, reopened ]
  #   branches: [ development, main ]

  workflow_dispatch:
  workflow_call: # for eas submit flow

jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'yarn'
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          token: ${{ secrets.EXPO_TOKEN }}
          packager: yarn
          expo-cache: true
          expo-version: 5.3.0
          eas-version: latest
      - name: Install dependencies
        run: yarn install
      - name: Build on EAS
        run: eas build --profile production --platform all --non-interactive