# This is a basic workflow to help you get started with Actions

name: Vercel production deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Git checkout
        uses: actions/checkout@v2
      
      # Use Node and yarn
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: 'yarn'
      
      # Add Expo action
      - name: Use Expo
        uses: expo/expo-github-action@v6
        with:
          token: ${{ secrets.EXPO_TOKEN }}
          packager: yarn
          expo-cache: true
          expo-version: 4.11.0
          
      # Install dependencies
      - name: Install dependencies
        run: yarn install
      
      # Build for web
      - name: Build for web
        run: expo build:web
        
      # Deploy to Vercel
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20.0.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-args: --prod
          vercel-project-name: ${{ secrets.VERCEL_PROJECT_NAME }}
          working-directory: ./web-build
